# Generated by Django 4.2.4 on 2023-09-05 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemon', '0004_alter_menuitem_feature_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitem', to='LittleLemon.menuitem'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
